// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvGtuafftoof9UAs9xVekxE3ktw2RIVlk',
    appId: '1:1098048921319:web:e30ed202c9ae7660978c42',
    messagingSenderId: '1098048921319',
    projectId: 'kkek-ef277',
    authDomain: 'kkek-ef277.firebaseapp.com',
    storageBucket: 'kkek-ef277.appspot.com',
    measurementId: 'G-RFKMFC9QXN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDstO8YnNyJyTHZ38NRW01yILK4pdTquXg',
    appId: '1:1098048921319:android:22189895a59650ce978c42',
    messagingSenderId: '1098048921319',
    projectId: 'kkek-ef277',
    storageBucket: 'kkek-ef277.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWady54jzbhDZj4YGfNMt7T4lqI7tfNE8',
    appId: '1:1098048921319:ios:574c30ab680ca610978c42',
    messagingSenderId: '1098048921319',
    projectId: 'kkek-ef277',
    storageBucket: 'kkek-ef277.appspot.com',
    iosClientId: '1098048921319-nki2c5eg3ctb5jbqco792jeb0a0dcurf.apps.googleusercontent.com',
    iosBundleId: 'com.example.kkek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWady54jzbhDZj4YGfNMt7T4lqI7tfNE8',
    appId: '1:1098048921319:ios:31f72a53fef3a79c978c42',
    messagingSenderId: '1098048921319',
    projectId: 'kkek-ef277',
    storageBucket: 'kkek-ef277.appspot.com',
    iosClientId: '1098048921319-iq7jadpm0otft9ejgp64kp3tlhh26d3t.apps.googleusercontent.com',
    iosBundleId: 'com.example.kkek.RunnerTests',
  );
}
